export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST'
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'
export const CREATE_COMPANY_FAIL = 'CREATE_COMPANY_FAIL'

export const ALL_COMPANIES_REQUEST = 'ALL_COMPANIES_REQUEST'
export const ALL_COMPANIES_SUCCESS = 'ALL_COMPANIES_SUCCESS'
export const ALL_COMPANIES_FAIL = 'ALL_COMPANIES_FAIL'

export const COMPANY_DETAILS_REQUEST = 'COMPANY_DETAILS_REQUEST'
export const COMPANY_DETAILS_SUCCESS = 'COMPANY_DETAILS_SUCCESS'
export const COMPANY_DETAILS_FAIL = 'COMPANY_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'